name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 👈 This is required to push tags!

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitHub Tag Action
        uses: anothrNick/github-tag-action@v1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 👈 Required for tag pushing
          DEFAULT_BUMP: patch                        # patch | minor | major
          WITH_V: true                               # results in v1.0.1 tag
